name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Nome_Solucao: SolidWorksCustomCommunicatioExtension
      Diretorio_Projeto_Wap: SolidWorksCustomCommunicatioExtension/bin/Release

    steps:
    - name: Enviar arquivo ZIP via HTTP POST com autenticação
      run: |
        echo "${{ github.repository }}"
        echo "${{ secrets.API_TOKEN }}"
        echo "$env:GITHUB_WORKSPACE"
