name: Configuração de pipeline para integradores

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Nome_Solucao: SolidWorksCustomCommunicatioExtension
      Diretorio_Projeto_Wap: SolidWorksCustomCommunicatioExtension/bin/Release

    steps:
    - name: Fazer checkout do código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Instalar .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Configurar MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Compilar a solução no modo Release
      run: msbuild $env:Nome_Solucao /p:Configuration=Release

    - name: Listar arquivos no diretório bin/Release
      run: dir SolidWorksCustomCommunicatioExtension/bin/Release

    - name: Criar arquivo ZIP dos artefatos de build
      run: |
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [IO.Compression.ZipFile]::CreateFromDirectory("$env:GITHUB_WORKSPACE/$env:Diretorio_Projeto_Wap", "$env:GITHUB_WORKSPACE/Release.zip")

    - name: Listar arquivos do repositório
      run: dir $env:GITHUB_WORKSPACE

    - name: Upload do artefato de build (arquivo ZIP)
      uses: actions/upload-artifact@v3
      with:
        name: Release.zip
        path: ${{ github.workspace }}/Release.zip

